export const artistData = {
    coverImage: "/assets/images/placeholders/ImagePlaceHolder(9).png",
    artistImage: "/assets/images/Avatar.png",
    artistName: "Animakid",
    artistBio: "The internet's friendliest designer kid.",
    Links: {
      twitter: "https://twitter.com",
      instagram: "https://instagram.com",
      website: "https://website.com",
      discord: "https://discord.com",
    },
    stats: {
      followers: 100,
      volume: 100,
      nfts: 100,
      collections: 50,
    },
  };

  export  const DiscoveredNFTs = [
    {
      nftImage: "/assets/images/placeholders/ImagePlaceholder(1).png",
      nftName: "Artwork",
      nftOwner: "Keepitreal",
      nftOwnerAvatar: "/assets/images/Avatar1.png",
      nftPrice: "0.5",
      hiestBid: "0.6",
    },
    {
      nftImage: "/assets/images/placeholders/ImagePlaceholder(2).png",
      nftName: "Artwork",
      nftOwner: "DigiLab",
      nftOwnerAvatar: "/assets/images/Avatar2.png",
      nftPrice: "0.5",
      hiestBid: "0.6",
    },
    {
      nftImage: "/assets/images/placeholders/ImagePlaceholder(3).png",
      nftName: "Artwork",
      nftOwner: "GravityOne",
      nftOwnerAvatar: "/assets/images/Avatar3.png",
      nftPrice: "0.5",
      hiestBid: "0.6",
    },
    {
      nftImage: "/assets/images/placeholders/ImagePlaceholder(4).png",
      nftName: "Artwork",
      nftOwner: "Juanie",
      nftOwnerAvatar: "/assets/images/Avatar4.png",
      nftPrice: "0.5",
      hiestBid: "0.6",
    },
    {
      nftImage: "/assets/images/placeholders/ImagePlaceholder(5).png",
      nftName: "Artwork",
      nftOwner: "BlueWhale",
      nftOwnerAvatar: "/assets/images/Avatar5.png",
      nftPrice: "0.5",
      hiestBid: "0.6",
    },
    {
      nftImage: "/assets/images/placeholders/ImagePlaceholder(6).png",
      nftName: "Artwork",
      nftOwner: "mr fox",
      nftOwnerAvatar: "/assets/images/Avatar6.png",
      nftPrice: "0.5",
      hiestBid: "0.6",
    },
    {
      nftImage: "/assets/images/placeholders/ImagePlaceholder(7).png",
      nftName: "Artwork",
      nftOwner: "Shroomie",
      nftOwnerAvatar: "/assets/images/Avatar7.png",
      nftPrice: "0.5",
      hiestBid: "0.6",
    },
  ];
  export  const TrendingCollectionsArray = [
    {
      ownerName: "MrFox",
      ownerImage: "/assets/images/placeholders/PrimaryPlaceholder.png",
      collectionName: "DSGN Animals",
      images: [
        "/assets/images/placeholders/PrimaryPlaceholder.png",
        "/assets/images/placeholders/ImagePlaceholder(1).png",
        "/assets/images/placeholders/ImagePlaceholder(2).png",
        "/assets/images/placeholders/ImagePlaceholder(3).png",
        "/assets/images/placeholders/ImagePlaceholder(4).png",
        "/assets/images/placeholders/PrimaryPlaceholder.png",
        "/assets/images/placeholders/ImagePlaceholder(1).png",
        "/assets/images/placeholders/ImagePlaceholder(2).png",
        "/assets/images/placeholders/ImagePlaceholder(3).png",
        "/assets/images/placeholders/ImagePlaceholder(4).png",
        "/assets/images/placeholders/PrimaryPlaceholder.png",
        "/assets/images/placeholders/ImagePlaceholder(1).png",
        "/assets/images/placeholders/ImagePlaceholder(2).png",
        "/assets/images/placeholders/ImagePlaceholder(3).png",
        "/assets/images/placeholders/ImagePlaceholder(4).png",
        "/assets/images/placeholders/PrimaryPlaceholder.png",
        "/assets/images/placeholders/ImagePlaceholder(1).png",
        "/assets/images/placeholders/ImagePlaceholder(2).png",
        "/assets/images/placeholders/ImagePlaceholder(3).png",
        "/assets/images/placeholders/ImagePlaceholder(4).png",
      ],
    },
    {
      ownerName: "Shroomie",
      ownerImage: "/assets/images/placeholders/PrimaryPlaceholder.png",
      collectionName: "Disco Machines",
      images: [
        "/assets/images/placeholders/PrimaryPlaceholder.png",
        "/assets/images/placeholders/ImagePlaceholder(7).png",
        "/assets/images/placeholders/ImagePlaceholder(6).png",
        "/assets/images/placeholders/ImagePlaceholder(5).png",
        "/assets/images/placeholders/ImagePlaceholder(4).png",
        "/assets/images/placeholders/PrimaryPlaceholder.png",
        "/assets/images/placeholders/ImagePlaceholder(7).png",
        "/assets/images/placeholders/ImagePlaceholder(6).png",
        "/assets/images/placeholders/ImagePlaceholder(5).png",
        "/assets/images/placeholders/ImagePlaceholder(4).png",
      ],
    },
    {
      ownerName: "John Doe",
      ownerImage: "/assets/images/placeholders/PrimaryPlaceholder.png",
      collectionName: "Magic Mushrooms",
      images: [
        "/assets/images/placeholders/PrimaryPlaceholder.png",
        "/assets/images/placeholders/ImagePlaceholder.png",
        "/assets/images/placeholders/ImagePlaceholder(7).png",
        "/assets/images/placeholders/ImagePlaceholder(6).png",
        "/assets/images/placeholders/ImagePlaceholder(5).png",
        "/assets/images/placeholders/ImagePlaceholder(4).png",
      ],
    },
    {
      ownerName: "John Doe",
      ownerImage: "/assets/images/placeholders/PrimaryPlaceholder.png",
      collectionName: "Magic Mushrooms",
      images: [
        "/assets/images/placeholders/PrimaryPlaceholder.png",
        "/assets/images/placeholders/ImagePlaceholder.png",
        "/assets/images/placeholders/ImagePlaceholder(7).png",
        "/assets/images/placeholders/ImagePlaceholder(6).png",
        "/assets/images/placeholders/ImagePlaceholder(5).png",
        "/assets/images/placeholders/ImagePlaceholder(4).png",
      ],
    },
  ];